import { Translations } from './types';

export const BOOKING_DEADLINE = new Date('2025-12-15T23:59:59');

export const SEAT_PRICE = 800;
export const SEATS_PER_TABLE = 8;
export const TABLE_PRICE = 6000; // Price for booking a whole table


export const TOTAL_MAIN_TABLES = 110;
export const TOTAL_RESERVE_TABLES = 10;


export const classData: { [key: string]: string[] } = {
    'อนุบาล': ['K.1A TP', 'K.1B TP', 'K.2A TP', 'K.2B TP', 'K.3A TP', 'K.3B TP', 'K.1A EP', 'K.1B EP', 'K.2A EP', 'K.2B EP', 'K.3A EP', 'K.3B EP'],
    'Kindergarten': ['K.1A TP', 'K.1B TP', 'K.2A TP', 'K.2B TP', 'K.3A TP', 'K.3B TP', 'K.1A EP', 'K.1B EP', 'K.2A EP', 'K.2B EP', 'K.3A EP', 'K.3B EP'],
    'โปรแกรมภาษาไทย': ['P.1A TP', 'P.1B TP', 'P.2A TP', 'P.2B TP', 'P.3A TP', 'P.3B TP', 'P.4A TP', 'P.4B TP', 'P.5A TP', 'P.5B TP', 'P.6A TP', 'P.6B TP', 'M.1A TP', 'M.1B TP', 'M.2A TP', 'M.2B TP', 'M.3A TP', 'M.3B TP', 'M.4A TP', 'M.5A TP', 'M.6A TP'],
    'Thai Program': ['P.1A TP', 'P.1B TP', 'P.2A TP', 'P.2B TP', 'P.3A TP', 'P.3B TP', 'P.4A TP', 'P.4B TP', 'P.5A TP', 'P.5B TP', 'P.6A TP', 'P.6B TP', 'M.1A TP', 'M.1B TP', 'M.2A TP', 'M.2B TP', 'M.3A TP', 'M.3B TP', 'M.4A TP', 'M.5A TP', 'M.6A TP'],
    'โปรแกรมภาษาอังกฤษ': ['P.1A EP', 'P.1B EP', 'P.2A EP', 'P.2B EP', 'P.3A EP', 'P.3B EP', 'P.4A EP', 'P.4B EP', 'P.5A EP', 'P.5B EP', 'P.6A EP', 'P.6B EP', 'M.1A EP', 'M.1B EP', 'M.2A EP', 'M.2B EP', 'M.3A EP', 'M.3B EP', 'M.4A EP', 'M.5A EP', 'M.6A EP'],
    'English Program': ['P.1A EP', 'P.1B EP', 'P.2A EP', 'P.2B EP', 'P.3A EP', 'P.3B EP', 'P.4A EP', 'P.4B EP', 'P.5A EP', 'P.5B EP', 'P.6A EP', 'P.6B EP', 'M.1A EP', 'M.1B EP', 'M.2A EP', 'M.2B EP', 'M.3A EP', 'M.3B EP', 'M.4A EP', 'M.5A EP', 'M.6A EP'],
    'เนอสเซอรี่': ['Nursery 1', 'Nursery 2'],
    'Nursery': ['Nursery 1', 'Nursery 2'],
};

export const calculateTotalPrice = (selectedSeats: string[]): number => {
    if (!selectedSeats || selectedSeats.length === 0) {
        return 0;
    }

    const seatsByTable: { [tableId: string]: string[] } = {};
    selectedSeats.forEach(seatId => {
        const tableId = seatId.split('-')[0];
        if (!seatsByTable[tableId]) {
            seatsByTable[tableId] = [];
        }
        seatsByTable[tableId].push(seatId);
    });

    let total = 0;
    for (const tableId in seatsByTable) {
        const numSeatsInTable = seatsByTable[tableId].length;
        if (numSeatsInTable === SEATS_PER_TABLE) {
            total += TABLE_PRICE;
        } else {
            total += numSeatsInTable * SEAT_PRICE;
        }
    }
    return total;
};

export const translations: Translations = {
    th: {
        headerTitle: "ระบบจองโต๊ะงานประจำปี 2568",
        headerSubtitle: "โรงเรียนสาธิตอุดมศึกษา อำเภอบางละมุง จังหวัดชลบุรี",
        eventDate: "วันที่ 19 ธันวาคม 2568 เวลา 18.00 – 22.30 น.",
        adminBtnText: "แอดมิน",
        navBooking: "จองโต๊ะ",
        navForm: "ข้อมูลผู้จอง",
        navAdmin: "แดชบอร์ด",
        tableLayoutTitle: "แผนผังโต๊ะงานประจำปี",
        mainTables: "โต๊ะหลัก",
        reserveTables: "โต๊ะสำรอง",
        stageLabel: "เวที",
        rowLabel: "แถวที่",
        legendAvailable: "ว่าง",
        legendSelected: "ที่เลือก",
        legendPartial: "จองบางส่วน",
        legendBooked: "จองแล้ว",
        summaryTitle: "สรุปการจอง",
        summarySeats: "จำนวนที่นั่งที่เลือก",
        summaryTotal: "ยอดรวม",
        proceedBtn: "ดำเนินการต่อ",
        clearBtn: "ล้างที่เลือก",
        seatNamesLabel: "หมายเลขที่นั่ง",
        formTitle: "กรอกข้อมูลผู้จอง",
        parentTitle: "ข้อมูลผู้ปกครอง",
        parentPrefixLabel: "คำนำหน้า",
        parentFirstNameLabel: "ชื่อจริง",
        parentLastNameLabel: "นามสกุล",
        parentPhoneLabel: "เบอร์โทรศัพท์",
        studentTitle: "ข้อมูลนักเรียน",
        studentPrefixLabel: "คำนำหน้า",
        studentFirstNameLabel: "ชื่อจริง",
        studentLastNameLabel: "นามสกุล",
        studentProgramLabel: "โปรแกรม",
        studentClassLabel: "ห้องเรียน",
        backToBookingBtn: "กลับไปเลือกโต๊ะ",
        confirmBookingBtn: "ยืนยันการจอง",
        adminLoginTitle: "เข้าสู่ระบบแอดมิน",
        usernameLabel: "ชื่อผู้ใช้",
        passwordLabel: "รหัสผ่าน",
        loginBtn: "เข้าสู่ระบบ",
        adminTitle: "แดชบอร์ดผู้ดูแลระบบ",
        totalBookingsLabel: "การจองทั้งหมด",
        totalSeatsBookedLabel: "ที่นั่งที่จองแล้ว",
        totalRevenueLabel: "รายได้รวม",
        availableSeatsLabel: "ที่นั่งว่าง",
        bookingListTitle: "รายการจอง",
        exportBtn: "ส่งออกเป็น Excel",
        logoutBtn: "ออกจากระบบ",
        filterByCustomerLabel: "ค้นหาตามชื่อผู้ปกครอง",
        filterByStudentLabel: "ค้นหาตามชื่อนักเรียน",
        searchPlaceholder: "ค้นหา...",
        clearFilterBtn: "ล้างตัวกรอง",
        bookingIdHeader: "รหัสการจอง",
        customerNameHeader: "ชื่อผู้ปกครอง",
        studentNameHeader: "ชื่อนักเรียน",
        amountHeader: "ยอดรวม",
        statusHeader: "สถานะ",
        actionsHeader: "รายละเอียด",
        viewDetailsBtn: "ดูรายละเอียด",
        editBtn: "แก้ไข",
        noResultsText: "ไม่พบผลลัพธ์ที่ตรงกัน",
        noBookingsYetText: "ยังไม่มีการจอง",
        confirmBookingTitle: "ยืนยันข้อมูลการจอง",
        confirmBookingMessage: "กรุณาตรวจสอบข้อมูลการจองของท่านให้ถูกต้องก่อนดำเนินการต่อ",
        saveBookingBtn: "บันทึกการจอง",
        editInfoBtn: "แก้ไขข้อมูล",
        bookingSuccessTitle: "จองสำเร็จ!",
        bookingSuccessMessage: "การจองของท่านได้รับการบันทึกเรียบร้อยแล้ว",
        paymentQrCodeTitle: "ชำระเงินผ่าน QR Code",
        bookingDetailsTitle: "รายละเอียดการจอง",
        saveAsPdfBtn: "บันทึกเป็น JPEG",
        closeBtn: "ปิด",
        errorText: "เกิดข้อผิดพลาด กรุณาลองใหม่อีกครั้ง",
        saveChangesBtn: "บันทึกการเปลี่ยนแปลง",
        cancelBtn: "ยกเลิก",
        bookingClosedTitle: "ปิดรับการจองแล้ว",
        bookingClosedMessage: "ขออภัย ระบบปิดรับการจองแล้ว หากมีข้อสงสัยกรุณาติดต่อโรงเรียน",
        adminOnlyText: "โหมดผู้ดูแลระบบ",
        lockedRowTooltip: "แถวนี้จะถูกปลดล็อคเมื่อแถวก่อนหน้าถูกจองเต็มทั้งหมดแล้ว",
        tableLabel: "โต๊ะ",
        seatsHeader: "ที่นั่งที่จอง",
        cancelBookingTitle: "ยกเลิกการจอง",
        selectItemsToCancel: "เลือกรายการที่จะยกเลิก",
        originalTotal: "ยอดรวมเดิม",
        newTotal: "ยอดรวมใหม่",
        confirmCancellationBtn: "ยืนยันการยกเลิก",
        seatsLabel: "ที่นั่ง",
        cancelledStatus: "ยกเลิกแล้ว",
        bookingCancelledSuccess: "ยกเลิกการจองสำเร็จแล้ว",
        cancelAction: "ยกเลิก",
        cancelEntireTable: "ยกเลิกทั้งโต๊ะ",
        selectAll: "เลือกทั้งหมด",
        currency: "บาท",
        lineOABookingBtn: "จองโต๊ะคลิกที่นี่",
        bookedByHeader: "แอดมินผู้ดำเนินการ",
        swalSuccessTitle: "สำเร็จ!",
        swalErrorTitle: "เกิดข้อผิดพลาด!",
        swalWarningTitle: "คำเตือน",
        swalInfoTitle: "โปรดทราบ",
        swalInvalidCredentials: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
        swalSelectSeatsFirst: "กรุณาเลือกที่นั่งก่อนดำเนินการต่อ",
        swalTablePartiallyBooked: "โต๊ะนี้มีที่นั่งถูกจองไปแล้ว ไม่สามารถเลือกทั้งโต๊ะได้",
        swalBookingError: "ไม่สามารถบันทึกการจองได้ กรุณาลองใหม่อีกครั้ง",
        swalNoDataToExport: "ไม่มีข้อมูลการจองให้ส่งออก",
        swalJpegError: "ไม่สามารถบันทึกเป็นไฟล์ JPEG ได้",
        swalJpegSuccess: "บันทึกไฟล์ JPEG สำเร็จแล้ว!",
        swalSelectItemsToCancel: "กรุณาเลือกรายการที่ต้องการยกเลิก",
        swalCancelSuccessTitle: "ยกเลิกแล้ว",
        swalCancelSuccessText: "การจองถูกยกเลิกเรียบร้อย",
    },
    en: {
        headerTitle: "Annual Party 2025 Booking System",
        headerSubtitle: "Satit Udomseuksa School, Bang Lamung, Chonburi",
        eventDate: "19 December 2025, 18:00 – 22:30",
        adminBtnText: "Admin",
        navBooking: "Booking",
        navForm: "Your Info",
        navAdmin: "Dashboard",
        tableLayoutTitle: "Annual Party Table Layout",
        mainTables: "Main Tables",
        reserveTables: "Reserve Tables",
        stageLabel: "Stage",
        rowLabel: "Row",
        legendAvailable: "Available",
        legendSelected: "Selected",
        legendPartial: "Partially Booked",
        legendBooked: "Booked",
        summaryTitle: "Booking Summary",
        summarySeats: "Selected Seats",
        summaryTotal: "Total Amount",
        proceedBtn: "Proceed",
        clearBtn: "Clear Selection",
        seatNamesLabel: "Seat Numbers",
        formTitle: "Enter Booker Information",
        parentTitle: "Parent Information",
        parentPrefixLabel: "Title",
        parentFirstNameLabel: "First Name",
        parentLastNameLabel: "Last Name",
        parentPhoneLabel: "Phone Number",
        studentTitle: "Student Information",
        studentPrefixLabel: "Title",
        studentFirstNameLabel: "First Name",
        studentLastNameLabel: "Last Name",
        studentProgramLabel: "Program",
        studentClassLabel: "Class",
        backToBookingBtn: "Back to Booking",
        confirmBookingBtn: "Confirm Booking",
        adminLoginTitle: "Admin Login",
        usernameLabel: "Username",
        passwordLabel: "Password",
        loginBtn: "Login",
        adminTitle: "Admin Dashboard",
        totalBookingsLabel: "Total Bookings",
        totalSeatsBookedLabel: "Seats Booked",
        totalRevenueLabel: "Total Revenue",
        availableSeatsLabel: "Seats Available",
        bookingListTitle: "Booking List",
        exportBtn: "Export to Excel",
        logoutBtn: "Logout",
        filterByCustomerLabel: "Filter by Parent Name",
        filterByStudentLabel: "Filter by Student Name",
        searchPlaceholder: "Search...",
        clearFilterBtn: "Clear Filter",
        bookingIdHeader: "Booking ID",
        customerNameHeader: "Parent Name",
        studentNameHeader: "Student Name",
        amountHeader: "Amount",
        statusHeader: "Status",
        actionsHeader: "Actions",
        viewDetailsBtn: "View",
        editBtn: "Edit",
        noResultsText: "No matching results found.",
        noBookingsYetText: "No bookings have been made yet.",
        confirmBookingTitle: "Confirm Booking Information",
        confirmBookingMessage: "Please review your booking details carefully before proceeding.",
        saveBookingBtn: "Save Booking",
        editInfoBtn: "Edit Information",
        bookingSuccessTitle: "Booking Successful!",
        bookingSuccessMessage: "Your booking has been confirmed.",
        paymentQrCodeTitle: "Pay via QR Code",
        bookingDetailsTitle: "Booking Details",
        saveAsPdfBtn: "Save as JPEG",
        closeBtn: "Close",
        errorText: "An error occurred. Please try again.",
        saveChangesBtn: "Save Changes",
        cancelBtn: "Cancel",
        bookingClosedTitle: "Booking is Closed",
        bookingClosedMessage: "We are sorry, the booking system is now closed. Please contact the school for any inquiries.",
        adminOnlyText: "Admin Mode",
        lockedRowTooltip: "This row will be unlocked when the previous row is fully booked.",
        tableLabel: "Table",
        seatsHeader: "Booked Seats",
        cancelBookingTitle: "Cancel Booking",
        selectItemsToCancel: "Select items to cancel",
        originalTotal: "Original Total",
        newTotal: "New Total",
        confirmCancellationBtn: "Confirm Cancellation",
        seatsLabel: "Seat",
        cancelledStatus: "Cancelled",
        bookingCancelledSuccess: "Booking has been cancelled successfully.",
        cancelAction: "Cancel",
        cancelEntireTable: "Cancel Entire Table",
        selectAll: "Select All",
        currency: "THB",
        lineOABookingBtn: "Book via LINE OA",
        bookedByHeader: "Action Performed By",
        swalSuccessTitle: "Success!",
        swalErrorTitle: "Error!",
        swalWarningTitle: "Warning",
        swalInfoTitle: "Info",
        swalInvalidCredentials: "Invalid username or password.",
        swalSelectSeatsFirst: "Please select seats before proceeding.",
        swalTablePartiallyBooked: "This table has booked seats and cannot be selected as a whole.",
        swalBookingError: "Could not save the booking. Please try again.",
        swalNoDataToExport: "There is no booking data to export.",
        swalJpegError: "Could not save the file as JPEG.",
        swalJpegSuccess: "JPEG file saved successfully!",
        swalSelectItemsToCancel: "Please select items to cancel.",
        swalCancelSuccessTitle: "Cancelled",
        swalCancelSuccessText: "The booking has been successfully cancelled.",
    },
};